"""Mailer table

Revision ID: 2106c05d3cd5
Revises: 
Create Date: 2022-05-29 10:51:49.874732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2106c05d3cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_email'), 'mail', ['email'], unique=False)
    op.create_index(op.f('ix_mail_firstname'), 'mail', ['firstname'], unique=False)
    op.create_index(op.f('ix_mail_lastname'), 'mail', ['lastname'], unique=False)
    op.create_index(op.f('ix_mail_message'), 'mail', ['message'], unique=False)
    op.create_index(op.f('ix_mail_subject'), 'mail', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_subject'), table_name='mail')
    op.drop_index(op.f('ix_mail_message'), table_name='mail')
    op.drop_index(op.f('ix_mail_lastname'), table_name='mail')
    op.drop_index(op.f('ix_mail_firstname'), table_name='mail')
    op.drop_index(op.f('ix_mail_email'), table_name='mail')
    op.drop_table('mail')
    # ### end Alembic commands ###
